### ISSUE TITLE
Recheck Lines 240 and 252

### ISSUE THREAD

**Issue by salimhurjuk** [ryancbutler/Citrix_Optimizer_Community_Template_Marketplace#2]
![image](https://user-images.githubusercontent.com/26679165/54091035-0be71500-43a1-11e9-8e56-8f7da0c31436.png)

Recheck Lines 240 and 252: Both are having the same service name. I don't think so Citrix Profile Management is needed to be disabled.

**Comment by ryancbutler** [comment]
@j81blog Thoughts here?

**Comment by j81blog** [comment]
Citrix Profile Manager service should be "ctxProfile". But note that the Desktop Ready Event logged by Citrix Profile Management (EventID 1000) is required for the Director to measure Login duration.

**Comment by salimhurjuk** [comment]
It means we should not disable this service.

**Comment by j81blog** [comment]
Best indeed not to disable it by default

**Comment by salimhurjuk** [comment]
OK, thanks @j81blog . I will not disable Citrix UPM Service. Hope you do the changes in Master File.

**Comment by ryancbutler** [comment]
@j81blog Could you make the change the and submit as a PR? Or do you want me to make the change?

**Comment by salimhurjuk** [comment]
@ryancbutler @j81blog Also, I think you need an upgrade to the template to CTXOE v2.

**Comment by ryancbutler** [comment]
Yes, the version will need to be bumped.

**Comment by j81blog** [comment]
I'm on it. Thank you for bringing this to my attention.

**Comment by j81blog** [comment]
@ryancbutler, I made the necessary changes.
